services:
  - type: web
    name: my-django-app
    env: docker
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString

databases:
  - name: mydatabase
    plan: free
    region: oregon
