# Generated by Django 5.1.5 on 2025-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='EDI_number',
            field=models.CharField(blank=True, help_text='Third party reference number for film booking', max_length=50, null=True, unique=True),
        ),
    ]
