# Generated by Django 4.2.4 on 2025-01-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showcreditlog",
            options={"ordering": ["created_on"]},
        ),
        migrations.AddField(
            model_name="showcreditlog",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="showcreditlog",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="showcreditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
