# Generated by Django 4.2.4 on 2025-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_showcreditlog_options_showcreditlog_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="relaxed_screening",
            field=models.BooleanField(
                default=False, help_text="Is this a relaxed screening?"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="subtitles",
            field=models.BooleanField(
                default=False, help_text="Does this show have subtitles?"
            ),
        ),
    ]
