# Generated by Django 4.2.4 on 2025-01-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_show_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='title',
        ),
    ]
