# Generated by Django 5.1.5 on 2025-01-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_show_relaxed_screening_show_subtitles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['eventtime'], 'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterModelOptions(
            name='showcreditlog',
            options={'ordering': ['created_on'], 'verbose_name': 'Show Credit Log', 'verbose_name_plural': 'Show Credit Logs'},
        ),
        migrations.AlterField(
            model_name='location',
            name='min_capacity',
            field=models.IntegerField(default=40, help_text='Minimum number of credits required for show confirmation'),
        ),
        migrations.AlterField(
            model_name='show',
            name='body',
            field=models.TextField(help_text='Description and details about the show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='eventtime',
            field=models.DateTimeField(help_text='Scheduled date and time of the show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='relaxed_screening',
            field=models.BooleanField(default=False, help_text='Will this be a relaxed screening?'),
        ),
        migrations.AlterField(
            model_name='show',
            name='subtitles',
            field=models.BooleanField(default=False, help_text='Do you want this show to have subtitles?'),
        ),
    ]
