# Generated by Django 5.1.5 on 2025-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_film_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
