# Generated by Django 5.1.5 on 2025-01-26 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_film_active_film_description_alter_film_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='IMDB code must be in the format "tt" followed by 7-8 digits (e.g., tt0111161)', regex='^tt\\d{7,8}$')]),
        ),
    ]
