# Generated by Django 5.1.5 on 2025-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_film_imdb_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='max_capacity',
            field=models.IntegerField(default=100, help_text='Maximum number of credits allowed for this venue'),
        ),
    ]
