# Generated by Django 5.1.5 on 2025-01-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_location_max_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email for the company', max_length=254, verbose_name='Head Office Email')),
            ],
            options={
                'verbose_name': 'Venue Owner',
                'verbose_name_plural': 'Venue Owners',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this venue is currently available for shows'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_email',
            field=models.EmailField(default='test@test.com', help_text='Direct contact email for the venue manager', max_length=254, verbose_name='Venue Manager Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The company or individual that owns this venue (optional for independent venues)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='blog.venueowner'),
        ),
    ]
